// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiRlIo17N71zMJqvMnGQBXbjxKJ6e1Gbs',
    appId: '1:970633298102:web:de944fbf1992e508966617',
    messagingSenderId: '970633298102',
    projectId: 'buttermillyauth',
    authDomain: 'buttermillyauth.firebaseapp.com',
    storageBucket: 'buttermillyauth.appspot.com',
    measurementId: 'G-J2L522770F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZQJnf9nB9tOBdo1UYXg5QvlY2A0mBKv0',
    appId: '1:970633298102:android:1f7b3bd687822379966617',
    messagingSenderId: '970633298102',
    projectId: 'buttermillyauth',
    storageBucket: 'buttermillyauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvTIlJo85PZH8DNc6XtqW8KGrtSERk76M',
    appId: '1:970633298102:ios:9add7b4c1f13a143966617',
    messagingSenderId: '970633298102',
    projectId: 'buttermillyauth',
    storageBucket: 'buttermillyauth.appspot.com',
    iosClientId: '970633298102-hljdsid93e80nvlht6033b6pelg81cl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.buttermilly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvTIlJo85PZH8DNc6XtqW8KGrtSERk76M',
    appId: '1:970633298102:ios:9add7b4c1f13a143966617',
    messagingSenderId: '970633298102',
    projectId: 'buttermillyauth',
    storageBucket: 'buttermillyauth.appspot.com',
    iosClientId: '970633298102-hljdsid93e80nvlht6033b6pelg81cl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.buttermilly',
  );
}
